### ISSUE TITLE
TypeError: config() got an unexpected keyword argument 'quantized_method'

### ISSUE THREAD

**Issue by opentld** [cqu20160901/yolov10_rknn_Cplusplus#2]
rknn-toolkit version: 1.7.5

--> Config model
Traceback (most recent call last):
  File "onnx2rknn_demo_ZQ.py", line 224, in <module>
    outputs = export_rknn_inference(input_img)
  File "onnx2rknn_demo_ZQ.py", line 165, in export_rknn_inference
    rknn.config(mean_values=[[0, 0, 0]], std_values=[[255, 255, 255]], quantized_algorithm='normal', quantized_method='channel', target_platform='rk3588')
TypeError: config() got an unexpected keyword argument 'quantized_method'

此外， target_platform='rk3588' 似乎也不认？

**Comment by cqu20160901** [comment]
rknn-toolkit version: 1.7.5 没有用过，1.3和1.6我用过是可以的

**Comment by opentld** [comment]
> rknn-toolkit version: 1.7.5 没有用过，1.3和1.6我用过是可以的

rknn-toolkit 还是 rknn-toolkit2 ？

**Comment by cqu20160901** [comment]
rknn-toolkit2




---Original---
From: ***@***.***&gt;
Date: Fri, Jun 21, 2024 18:25 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cqu20160901/yolov10_rknn_Cplusplus] TypeError: config() got anunexpected keyword argument 'quantized_method' (Issue #2)




  
rknn-toolkit version: 1.7.5 没有用过，1.3和1.6我用过是可以的
  
rknn-toolkit 还是 rknn-toolkit2 ？
